### ISSUE TITLE
Updating mobile toolbar

### ISSUE THREAD

**Issue by JiliTheSpaceboy** [celestiamobile/MobileCelestia#54]
Currently the mobile toolbar is rather clunky and difficult to use, contributing to numerous complaints about people not being able to move around. I believe it is a good idea to update this.

Ideas which have been suggested on Discord are:
- (Chara) Remove the + and - buttons (we already have pinch zooming which serves the same purpose), opening up two slots.
- (Chara) Put the 'Go' button in the tool bar (instead of inside Information).
- (pedroJ) Put the Search button in the tool bar.
- (TheLostProbe) Rename 'Star Browser' to 'Object Browser' or 'Celestial Browser' (also see #35).
- (Chara) For vertical screens, move the toolbar to the bottom so it blocks less space. Move the text at the bottom to just above the toolbar.

**Comment by levinli303** [comment]
For + and - buttons, I actually want to know how well the current pinch gesture works. I definitely want to get rid of these buttons (moving them into camera control).

"search" is a good candidate to put in the toolbar, but i'm not sure about "go", since tapping multiple times could lead to bad behaviors.

for the last item, i think it would be best to have some example apps that we can learn from, their existing UI.

**Comment by levinli303** [comment]
Removing +/- is done in https://github.com/celestiamobile/MobileCelestia/pull/55 and https://github.com/celestiamobile/AndroidCelestia/pull/68

**Comment by JiliTheSpaceboy** [comment]
> "search" is a good candidate to put in the toolbar, but i'm not sure about "go", since tapping multiple times could lead to bad behaviors.

Bad behaviors?

> for the last item, i think it would be best to have some example apps that we can learn from, their existing UI.

I don't know about any specific examples, but I'm pretty sure a lot of mobile apps used vertically generally place their toolbar at the bottom.

**Comment by levinli303** [comment]
> Bad behaviors?

tapping on Go (`g` key command) multiple times would result in a getting to close to the object.

**Comment by JiliTheSpaceboy** [comment]
> > Bad behaviors?
> 
> tapping on Go (`g` key command) multiple times would result in a getting too close to the object.

I don't really see why this is a reason to not include Go into the toolbar. It's the user's problem if they mash the button and end up getting too close to the object than they'd like.

**Comment by levinli303** [comment]
> I don't really see why this is a reason to not include Go into the toolbar. It's the user's problem if they mash the button and end up getting too close to the object than they'd like.

the only way to add a go button in toolbar is that the action should be persistent to give a better experience. i do not want to just bring the `g` command here. i'd like it to be implemented in a different way.

What i have in mind is that:
1. if the object is within NUM x radius distance, do nothing.
2. If the object is not within NUM x radius, use goToLonLat with distance = NUM * radius, longitude = xxx, latitude = xxx

**Comment by JiliTheSpaceboy** [comment]
Still don't see what the problem is, but sure I guess.

**Comment by levinli303** [comment]
For the last item, i am exploring with BottomAppBar on Android, it looks like this in potrait mode, landscape mode will keep the old appearance:

![Screenshot_20231024-103702](https://github.com/celestiamobile/MobileCelestia/assets/17924287/2d2e81f4-4d95-4bc2-ab09-dc01bc96e6ec)

**Comment by levinli303** [comment]
i am tempted to allow customization for the items in toolbar including what items users want to put and in what order.

**Comment by JiliTheSpaceboy** [comment]
> i am tempted to allow customization for the items in toolbar including what items users want to put and in what order.

That's a good idea. I'd like to see us being able to tailor our toolbar to fit our own preferences.

**Comment by levinli303** [comment]
I have not started working on it yet but i think customization should be part of Celestia PLUS on release (should be in 1.6.2).

I will decide if customization will be added as standard feature in the future.

**Comment by levinli303** [comment]
iOS design

![IMG_7773](https://github.com/celestiamobile/MobileCelestia/assets/17924287/9c0d639b-cb4b-4019-83ac-e51794f98b04)

**Comment by levinli303** [comment]
Done in 1.6.3
